### ISSUE TITLE
Change encryption 

### ISSUE THREAD

**Issue by jinxx0** [ArtyomArtamonov/EncryptedWebsocketChat#1]
RSA is cracked...

**Comment by nt4f04uNd** [comment]
@ArtyomArtamonov change the rsa key length to be at least 2048
https://github.com/ArtyomArtamonov/EncryptedWebsocketChat/blob/d93bfbfd70fe978ccd68e7766f34e1c3aab64c0c/modules/encryption.py#L6-L8
